version: '3.2'

services:
  oidc:
    image: oidc
    build: .
    env_file:
      - ./.env
    networks:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - ./keystore:/usr/src/app/local

  mongo:
    image: mongo:3.6-jessie
    ports:
      - 27017:27017

  redis:
    image: redis:3-alpine
    networks:
      - redis
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
      - ./redis:/usr/local/etc/redis

networks:
  mongodb:
  redis: