module.exports = {
  address: ['address'],
  email: ['email', 'email_verified'],
  openid: ['sub'],
  profile: [
    'birthdate',
    'family_name',
    'gender',
    'given_name',
    'locale',
    'middle_name',
    'name',
    'nickname',
    'picture',
    'preferred_username',
    'profile',
    'updated_at',
    'website',
    'zoneinfo',
  ],
  username: ['email', 'preferred_username'],
};
